version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12000:8000"
    volumes:
      - .:/var/www/html
      - ./storage/app/events:/var/www/html/storage/app/events
    environment:
      - DB_CONNECTION=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=rach_website
      - DB_USERNAME=rach_user
      - DB_PASSWORD=rach_password
    depends_on:
      - mariadb
    networks:
      - rach-network

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rach_website
      MYSQL_USER: rach_user
      MYSQL_PASSWORD: rach_password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M
      --max-connections=200
      --query-cache-type=1
      --query-cache-size=32M
    networks:
      - rach-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mariadb
    networks:
      - rach-network

volumes:
  mariadb_data:
    driver: local

networks:
  rach-network:
    driver: bridge